"use client";

import { useEffect, useState } from "react";
import { Download, Lock } from "lucide-react";
import Card, { CardHeader } from "@/components/ui/Card";
import { procurementApi, type ActivityEvent } from "@/lib/api";
import { activityActionLabel, displayCheckName } from "@/lib/recordUtils";

function statusColor(action: string) { if (action.includes("FAIL") || action.includes("DO_NOT_SELECT")) return "text-rose"; if (action.includes("FLAG") || action.includes("RFI")) return "text-amber"; if (action.includes("PASS") || action.includes("READY")) return "text-cyan"; return "text-violet"; }
function exportCsv(rows: ActivityEvent[]) { const values = [["Timestamp", "Bid ID", "Check", "Action", "Rule", "Evidence"], ...rows.map((event) => [event.timestamp, event.bid_id, event.check_name, event.action, event.rule, event.evidence])]; const csv = values.map((row) => row.map((value) => `"${String(value).replaceAll('"', '""')}"`).join(",")).join("\n"); const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "po-lice-activity.csv"; anchor.click(); URL.revokeObjectURL(url); }

export default function AuditPage() {
  const [events, setEvents] = useState<ActivityEvent[]>([]);
  const [state, setState] = useState<"loading" | "ready" | "offline">("loading");
  useEffect(() => { let active = true; procurementApi.activity().then((items) => { if (active) { setEvents(items); setState("ready"); } }).catch(() => active && setState("offline")); return () => { active = false; }; }, []);
  return <div className="space-y-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="flex items-center gap-2 text-2xl font-bold tracking-tight text-text"><Lock className="h-5 w-5 text-cyan" /> Activity log</h1><p className="mt-1 text-sm text-text/50">Timestamped checks and reviewer actions.</p></div><button type="button" onClick={() => exportCsv(events)} disabled={state !== "ready" || events.length === 0} className="inline-flex items-center gap-2 rounded-lg bg-cyan/15 px-4 py-2 text-sm font-medium text-cyan transition-colors hover:bg-cyan/25 disabled:cursor-not-allowed disabled:opacity-40"><Download className="h-4 w-4" /> Export CSV</button></div>{state === "offline" && <p className="rounded-lg border border-amber/25 bg-amber/5 px-4 py-2.5 text-sm text-amber/90">The activity service is unavailable. No activity is shown or inferred.</p>}<Card><CardHeader title={state === "ready" ? `${events.length} recorded events` : "Recorded events"} caption={state === "ready" ? "Export includes the server-recorded activity currently shown." : "Connect the activity service to view and export events."} /><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b border-white/10 text-left text-[11px] uppercase tracking-wide text-text/40"><th className="px-4 py-2.5 font-medium">Timestamp</th><th className="px-4 py-2.5 font-medium">Bid</th><th className="px-4 py-2.5 font-medium">Compliance check</th><th className="px-4 py-2.5 font-medium">Action</th><th className="px-4 py-2.5 font-medium">Rule</th><th className="px-4 py-2.5 font-medium">Evidence</th></tr></thead><tbody className="font-mono text-[12px]">{state === "loading" ? <tr><td colSpan={6} className="px-4 py-10 text-center text-text/40">Loading activity…</td></tr> : events.length ? events.map((event) => <tr key={event.id} className="border-b border-white/5 align-top hover:bg-white/[0.02]"><td className="whitespace-nowrap px-4 py-2.5 text-text/50">{new Date(event.timestamp).toLocaleString()}</td><td className="whitespace-nowrap px-4 py-2.5 text-text/80">{event.bid_id}</td><td className="whitespace-nowrap px-4 py-2.5 text-text/70">{displayCheckName(event.check_name)}</td><td className={`whitespace-nowrap px-4 py-2.5 font-bold ${statusColor(event.action)}`}>{activityActionLabel(event.action)}</td><td className="max-w-[280px] px-4 py-2.5 text-text/55">{event.rule}</td><td className="max-w-[320px] px-4 py-2.5 text-text/40">{event.evidence}</td></tr>) : <tr><td colSpan={6} className="px-4 py-10 text-center text-text/40">No server-recorded events yet.</td></tr>}</tbody></table></div></Card></div>;
}
