"use client";

import Link from "next/link";
import { ChangeEvent, FormEvent, useEffect, useMemo, useState } from "react";
import { CheckCircle2, Download, FileUp, LoaderCircle, Mail, RefreshCw, Upload } from "lucide-react";
import Card, { CardHeader } from "@/components/ui/Card";
import BidFlowState from "@/components/bid/BidFlowState";
import PatrolBadge from "@/components/bid/PatrolBadge";
import TCOSlider from "@/components/tco-slider";
import { ActivityEvent, checkFor, liveApi, LiveBid, money, reviewLabel } from "@/lib/api";
import { sampleBidById, sampleBids } from "@/lib/demoFallback";

const CHECKS = [
  ["BUILDING_PATROL", "Engineering"], ["GREEN_PATROL", "Carbon"], ["VICE_SQUAD", "Vendor reliability"], ["TRAFFIC_CONTROL", "Schedule impact"],
] as const;

function ErrorMessage({ error }: { error: string | null }) {
  return error ? <p role="alert" className="rounded-lg border border-rose/30 bg-rose/10 px-3 py-2 text-sm text-rose">{error}</p> : null;
}

function SampleNotice() {
  return <div className="rounded-lg border border-indigo/30 bg-indigo/10 px-4 py-3 text-sm text-indigo"><strong>Sample data</strong> — no uploaded bid is being reviewed. These records demonstrate the interface only; they are not source evidence and cannot record actions.</div>;
}

function UploadBid({ onUploaded }: { onUploaded: (bid: LiveBid) => void }) {
  const [file, setFile] = useState<File | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  async function submit(event: FormEvent) {
    event.preventDefault();
    if (!file) return setError("Choose a PDF to review.");
    setBusy(true); setError(null);
    try { onUploaded(await liveApi.upload(file)); setFile(null); }
    catch (reason) { setError(reason instanceof Error ? reason.message : "Upload failed."); }
    finally { setBusy(false); }
  }
  return <Card accent="#38BDF8"><CardHeader title="Upload bid" caption="Upload a text-based procurement PDF. PO-LICE stores the source locally, extracts stated values, then runs deterministic checks." />
    <form onSubmit={submit} className="flex flex-col gap-3 p-4 sm:flex-row sm:items-end"><label className="min-w-0 flex-1"><span className="sr-only">Bid PDF</span><input type="file" accept="application/pdf,.pdf" onChange={(event: ChangeEvent<HTMLInputElement>) => setFile(event.target.files?.[0] ?? null)} className="block w-full rounded-lg border border-white/10 bg-inset px-3 py-2 text-sm text-text file:mr-3 file:border-0 file:bg-transparent file:text-cyan" /></label><button disabled={busy} className="inline-flex h-10 items-center justify-center gap-2 rounded-lg bg-cyan px-4 text-sm font-semibold text-bg disabled:opacity-55"><Upload className="h-4 w-4" />{busy ? "Processing…" : "Upload and check"}</button></form><div className="px-4 pb-4"><ErrorMessage error={error} /></div></Card>;
}

export function ReviewQueue() {
  const [bids, setBids] = useState<LiveBid[]>([]); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [sampleMode, setSampleMode] = useState(false);
  const refresh = async () => { setLoading(true); try { const records = await liveApi.listBids(); setBids(records.length ? records : sampleBids); setSampleMode(records.length === 0); setError(null); } catch { setBids(sampleBids); setSampleMode(true); setError(null); } finally { setLoading(false); } };
  useEffect(() => { void refresh(); }, []);
  const hardFailures = bids.filter((bid) => bid.scorecard.recommendation === "REJECT").length;
  return <div className="space-y-6 pb-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="font-mono text-xs uppercase tracking-widest text-blue">Review queue</p><h1 className="mt-1 text-2xl font-bold tracking-tight text-text">Submitted bids</h1><p className="mt-1 max-w-2xl text-sm text-text/55">Source PDFs and their deterministic compliance results. A reviewer, not the system, authorises the next action.</p></div><button onClick={() => void refresh()} className="inline-flex items-center gap-2 text-xs text-text/60 hover:text-cyan"><RefreshCw className="h-3.5 w-3.5" /> Refresh</button></div>
    <UploadBid onUploaded={(bid) => { setBids((current) => [bid, ...current.filter((record) => !record.is_sample)]); setSampleMode(false); }} />
    {sampleMode && <SampleNotice />}
    <div className="grid gap-3 sm:grid-cols-3"><Metric label="Submitted" value={String(bids.length)} /><Metric label="Blocked selection" value={String(hardFailures)} /><Metric label="Needs review" value={String(bids.length - hardFailures)} /></div><ErrorMessage error={error} />
    <Card><CardHeader title="Bid list" caption="Open a record to inspect the extracted source data and rule evidence." />{loading ? <Loading /> : bids.length === 0 ? <Empty /> : <div className="overflow-x-auto"><table className="w-full min-w-[700px] text-sm"><thead><tr className="border-b border-white/10 text-left text-[11px] uppercase tracking-wide text-text/40"><th className="px-4 py-3">Vendor</th><th className="px-4 py-3">Equipment</th><th className="px-4 py-3">Submitted</th><th className="px-4 py-3">Review state</th><th className="px-4 py-3"></th></tr></thead><tbody>{bids.map((bid) => <tr key={bid.id} className="border-b border-white/5"><td className="px-4 py-3 font-medium text-text">{bid.source.vendor_name}</td><td className="px-4 py-3 text-text/60">{bid.source.equipment.equipment_type} · {bid.source.equipment.model_number}</td><td className="px-4 py-3 text-xs text-text/50">{bid.is_sample ? "Sample record" : new Date(bid.submitted_at).toLocaleString()}</td><td className="px-4 py-3"><ReviewPill bid={bid} /></td><td className="px-4 py-3"><Link className="text-xs font-semibold text-cyan hover:underline" href={`/bids/${bid.id}`}>Open review</Link></td></tr>)}</tbody></table></div>}</Card></div>;
}

export function BidComparison() {
  const [bids, setBids] = useState<LiveBid[]>([]); const [selected, setSelected] = useState<string[]>([]); const [error, setError] = useState<string | null>(null); const [sampleMode, setSampleMode] = useState(false);
  useEffect(() => { liveApi.listBids().then((records) => { const shown = records.length ? records : sampleBids; setBids(shown); setSampleMode(records.length === 0); setSelected(shown.slice(0, 3).map((bid) => bid.id)); }).catch(() => { setBids(sampleBids); setSampleMode(true); setSelected(sampleBids.map((bid) => bid.id)); }); }, []);
  const shown = bids.filter((bid) => selected.includes(bid.id));
  const toggle = (id: string) => setSelected((current) => current.includes(id) ? current.filter((value) => value !== id) : current.length < 3 ? [...current, id] : current);
  return <div className="space-y-6"><div><p className="font-mono text-xs uppercase tracking-widest text-blue">Bid comparison</p><h1 className="mt-1 text-2xl font-bold tracking-tight text-text">Compare uploaded bids</h1><p className="mt-1 text-sm text-text/55">Choose up to three submitted records. Comparisons only use extracted source values and deterministic results.</p></div><ErrorMessage error={error} />
    {sampleMode && <SampleNotice />}{bids.length === 0 && !error ? <Card><Empty /></Card> : <><Card><CardHeader title="Selected bids" caption="Up to three records can be compared at once." /><div className="flex flex-wrap gap-2 p-4">{bids.map((bid) => <label key={bid.id} className="flex cursor-pointer items-center gap-2 rounded-lg border border-white/10 px-3 py-2 text-xs text-text/70"><input type="checkbox" checked={selected.includes(bid.id)} disabled={!selected.includes(bid.id) && selected.length >= 3} onChange={() => toggle(bid.id)} className="accent-[#38BDF8]" />{bid.source.vendor_name}</label>)}</div></Card><Card><CardHeader title="Comparison" caption="A hard failure blocks selection; colour is supported by the explicit status label." /><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead><tr className="border-b border-white/10 text-left text-[11px] uppercase tracking-wide text-text/40"><th className="px-4 py-3">Bid</th><th className="px-4 py-3">Upfront cost</th>{CHECKS.map(([, label]) => <th key={label} className="px-4 py-3">{label}</th>)}<th className="px-4 py-3">5-year cost</th><th className="px-4 py-3">Review state</th></tr></thead><tbody>{shown.map((bid) => <tr key={bid.id} className="border-b border-white/5"><td className="px-4 py-3"><Link href={`/bids/${bid.id}`} className="font-medium text-text hover:text-cyan">{bid.source.vendor_name}</Link><p className="text-xs text-text/45">{bid.source.equipment.model_number}</p></td><td className="px-4 py-3 font-mono text-text/75">{money(bid.source.bid_amount_inr)}</td>{CHECKS.map(([name]) => <td key={name} className="px-4 py-3">{checkFor(bid, name) && <PatrolBadge status={checkFor(bid, name)!.status} size="sm" />}</td>)}<td className="px-4 py-3 font-mono text-text/75">{money(bid.scorecard.calculated_tco2_inr)}</td><td className="px-4 py-3"><ReviewPill bid={bid} /></td></tr>)}</tbody></table></div></Card></>}</div>;
}

export function BidReview({ bidId }: { bidId: string }) {
  const [bid, setBid] = useState<LiveBid | null>(null); const [events, setEvents] = useState<ActivityEvent[]>([]); const [error, setError] = useState<string | null>(null); const [tab, setTab] = useState<"summary" | "source" | "checks" | "impact" | "activity">("summary"); const [note, setNote] = useState(""); const [busy, setBusy] = useState(false);
  const load = async () => { const fallback = sampleBidById(bidId); if (fallback) { setBid(fallback); setEvents([]); return; } try { const record = await liveApi.bid(bidId); setBid(record); setEvents(await liveApi.activity(bidId)); } catch (reason) { setError(reason instanceof Error ? reason.message : "Bid could not be loaded."); } };
  useEffect(() => { void load(); }, [bidId]);
  async function addAction(action: "RFI_DRAFT_APPROVED" | "REVIEWED_DO_NOT_SELECT" | "REVIEWED_READY_FOR_DECISION") { if (bid?.is_sample) return setError("Sample data cannot record reviewer actions."); if (note.trim().length < 3) return setError("Add a short reviewer note before recording this action."); setBusy(true); try { await liveApi.action(bidId, action, note.trim()); setNote(""); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not record action."); } finally { setBusy(false); } }
  if (!bid) return <div className="space-y-4"><ErrorMessage error={error} />{!error && <Loading />}</div>;
  const hardFailure = bid.scorecard.recommendation === "REJECT";
  const fields = [["Power draw", bid.source.equipment.power_draw_kw, "kW"], ["Cooling capacity", bid.source.equipment.cooling_capacity_kw, "kW"], ["Equipment width", bid.source.equipment.width_m, "m"], ["Embodied carbon", bid.source.equipment.embodied_carbon_factor, "kgCO2e"], ["Delivery commitment", bid.source.promised_delivery_weeks, "weeks"], ["Safety certificate", bid.source.has_osha_cert == null ? null : bid.source.has_osha_cert ? "Present" : "Missing", ""]];
  return <div className="space-y-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><Link href="/bids" className="text-xs text-text/55 hover:text-cyan">← Back to comparison</Link><h1 className="mt-2 text-2xl font-bold text-text">{bid.source.vendor_name}</h1><p className="mt-1 text-sm text-text/55">{bid.source.equipment.equipment_type} · {bid.source.equipment.model_number} · {bid.filename}</p></div><ReviewPill bid={bid} /></div><BidFlowState />
    <div className="overflow-x-auto border-b border-white/10"><div className="flex min-w-max gap-1">{(["summary", "source", "checks", "impact", "activity"] as const).map((id) => <button key={id} onClick={() => setTab(id)} className={`border-b-2 px-3 py-2.5 text-xs font-medium capitalize ${tab === id ? "border-cyan text-cyan" : "border-transparent text-text/55"}`}>{id === "source" ? "Source data" : tabLabel(id)}</button>)}</div></div><ErrorMessage error={error} />
    {tab === "summary" && <div className="grid gap-5 lg:grid-cols-[1fr_340px]"><Card accent={hardFailure ? "#F43F5E" : "#38BDF8"} className="p-5"><p className="font-mono text-[10px] uppercase tracking-wider text-cyan">Review state</p><h2 className="mt-1 text-lg font-semibold text-text">{hardFailure ? "Selection is blocked until the failed checks are resolved" : "Review cited evidence before recording a decision"}</h2><p className="mt-2 text-sm text-text/60">The result is produced by deterministic rules. It is not a purchase-order approval.</p><div className="mt-4 flex flex-wrap gap-2">{bid.scorecard.patrol_results.map((check) => <PatrolBadge key={check.patrol_name} status={check.status} />)}</div></Card><Card><CardHeader title="Reviewer action" caption="This action is saved to the local activity record." /><div className="space-y-3 p-4"><textarea value={note} onChange={(event) => setNote(event.target.value)} placeholder="Reviewer note" className="min-h-24 w-full rounded-lg border border-white/10 bg-inset p-3 text-sm text-text" /><button disabled={busy} onClick={() => void addAction(hardFailure ? "RFI_DRAFT_APPROVED" : "REVIEWED_READY_FOR_DECISION")} className="inline-flex w-full items-center justify-center gap-2 rounded-lg bg-cyan px-3 py-2 text-sm font-semibold text-bg disabled:opacity-50">{hardFailure ? <Mail className="h-4 w-4" /> : <CheckCircle2 className="h-4 w-4" />}{hardFailure ? "Record reviewed RFI draft" : "Record reviewer decision"}</button></div></Card></div>}
    {tab === "source" && <div className="space-y-5"><Card><CardHeader title="Extracted source data" caption={bid.is_sample ? "Sample values for interface demonstration; no source PDF is available." : "Values are only shown when stated in the uploaded document. Missing values remain missing."} right={!bid.is_sample ? <a href={liveApi.sourceUrl(bid.id)} target="_blank" rel="noreferrer" className="text-xs text-cyan hover:underline">Open source PDF</a> : undefined} /><div className="overflow-x-auto"><table className="w-full text-sm"><tbody>{fields.map(([label, value, unit]) => <tr key={String(label)} className="border-b border-white/5"><td className="px-4 py-3 text-text/60">{label}</td><td className="px-4 py-3 font-mono text-text">{value == null ? "Not extracted" : `${value}${unit ? ` ${unit}` : ""}`}</td></tr>)}</tbody></table></div></Card><Card><CardHeader title="Document metadata" /><div className="grid gap-3 p-4 text-sm text-text/65 sm:grid-cols-3"><p>Author: {bid.source.document_metadata.author || "Not stated"}</p><p>Created: {bid.source.document_metadata.creation_date || "Not stated"}</p><p>Creator: {bid.source.document_metadata.creator_tool || "Not stated"}</p></div></Card></div>}
    {tab === "checks" && <div className="grid gap-4 lg:grid-cols-2">{bid.scorecard.patrol_results.map((check) => <Card key={check.patrol_name} className="p-4"><div className="flex items-start justify-between gap-3"><div><h2 className="font-semibold text-text">{CHECKS.find(([name]) => name === check.patrol_name)?.[1] ?? check.patrol_name}</h2><p className="mt-2 text-sm text-text/60">{check.reason}</p></div><PatrolBadge status={check.status} size="sm" /></div><p className="mt-4 font-mono text-[11px] text-text/45">Rule: {check.rule_broken || "No exception"}</p><pre className="mt-3 overflow-x-auto rounded bg-inset p-3 text-[11px] text-text/65">{JSON.stringify(check.evidence, null, 2)}</pre></Card>)}</div>}
    {tab === "impact" && <div className="space-y-5"><EvidenceCascade bid={bid} /><Card><CardHeader title="Five-year risk-adjusted cost" caption="The recorded calculation combines the extracted bid amount, the configured five-year operating/carbon allowance, and deterministic schedule penalty." /><div className="grid gap-4 p-5 sm:grid-cols-3"><Metric label="Upfront cost" value={money(bid.source.bid_amount_inr)} /><Metric label="5-year cost" value={money(bid.scorecard.calculated_tco2_inr)} /><Metric label="Selection state" value={reviewLabel(bid.scorecard.recommendation)} /></div></Card>{bid.source.bid_amount_inr != null && <TCOSlider baseCapexCr={bid.source.bid_amount_inr / 10_000_000} />}</div>}
    {tab === "activity" && <Card><CardHeader title="Bid activity" caption="Persisted check results and reviewer actions." />{events.length ? <ul className="divide-y divide-white/5">{events.map((event) => <li key={event.id} className="p-4"><p className="text-sm text-text">{event.action} <span className="text-text/45">· {event.check_name}</span></p><p className="mt-1 text-xs text-text/55">{event.evidence}</p><p className="mt-1 text-[11px] text-text/40">{new Date(event.timestamp).toLocaleString()}</p></li>)}</ul> : <Empty />}</Card>}</div>;
}

export function ActivityLog() {
  const [events, setEvents] = useState<ActivityEvent[]>([]);
  const [bids, setBids] = useState<LiveBid[]>([]);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { Promise.all([liveApi.activity(), liveApi.listBids()]).then(([rows, records]) => { setEvents(rows); setBids(records); }).catch((reason) => setError(reason.message)); }, []);
  const names = useMemo(() => new Map(bids.map((bid) => [bid.id, bid.source.vendor_name])), [bids]);
  function exportCsv() {
    const escape = (value: string) => `"${value.replaceAll('"', '""')}"`;
    const csv = [["Timestamp", "Bid", "Check", "Action", "Rule", "Evidence"], ...events.map((event) => [event.timestamp, names.get(event.bid_id) || event.bid_id, event.check_name, event.action, event.rule, event.evidence])].map((row) => row.map(escape).join(",")).join("\n");
    const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" }));
    const link = document.createElement("a"); link.href = url; link.download = "po-lice-activity.csv"; link.click(); URL.revokeObjectURL(url);
  }
  return <div className="space-y-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-bold text-text">Activity log</h1><p className="mt-1 text-sm text-text/55">Persistent calculation and reviewer events for uploaded bids.</p></div><button onClick={exportCsv} disabled={!events.length} className="inline-flex items-center gap-2 rounded-lg border border-cyan/30 bg-cyan/10 px-3 py-2 text-xs font-semibold text-cyan disabled:opacity-40"><Download className="h-3.5 w-3.5" />Export CSV</button></div><ErrorMessage error={error} /><Card><CardHeader title={`${events.length} recorded events`} caption="Entries persist locally across refreshes." />{events.length ? <div className="overflow-x-auto"><table className="w-full min-w-[850px] text-sm"><thead><tr className="border-b border-white/10 text-left text-[11px] uppercase text-text/40"><th className="px-4 py-3">Time</th><th className="px-4 py-3">Bid</th><th className="px-4 py-3">Check</th><th className="px-4 py-3">Action</th><th className="px-4 py-3">Evidence</th></tr></thead><tbody>{events.map((event) => <tr key={event.id} className="border-b border-white/5"><td className="px-4 py-3 text-xs text-text/50">{new Date(event.timestamp).toLocaleString()}</td><td className="px-4 py-3 text-text/75">{names.get(event.bid_id) || event.bid_id}</td><td className="px-4 py-3 text-text/65">{event.check_name}</td><td className="px-4 py-3 font-mono text-text">{event.action}</td><td className="px-4 py-3 text-xs text-text/55">{event.evidence}</td></tr>)}</tbody></table></div> : <Empty />}</Card></div>;
}

function ReviewPill({ bid }: { bid: LiveBid }) { const state = bid.scorecard.recommendation; const tone = state === "REJECT" ? "text-rose border-rose/30 bg-rose/10" : state === "RECOMMENDED" ? "text-cyan border-cyan/30 bg-cyan/10" : "text-amber border-amber/30 bg-amber/10"; return <span className={`inline-flex rounded border px-2 py-1 text-[10px] font-bold uppercase ${tone}`}>{reviewLabel(state)}</span>; }
function EvidenceCascade({ bid }: { bid: LiveBid }) {
  const findings = bid.scorecard.patrol_results.filter((check) => check.status !== "PASS");
  return <Card><CardHeader title="Evidence cascade" caption="Only failed or flagged deterministic checks appear here; select Checks for the cited inputs and rule details." /><div className="overflow-x-auto p-4"><div className="flex min-w-max items-stretch gap-3">{findings.length ? findings.map((check) => <div key={check.patrol_name} className="w-64 rounded-lg border border-white/10 bg-inset p-3"><p className={`font-mono text-[10px] font-bold uppercase ${check.status === "FAIL" ? "text-rose" : "text-amber"}`}>{CHECKS.find(([name]) => name === check.patrol_name)?.[1] ?? check.patrol_name} · {check.status}</p><p className="mt-2 text-xs leading-relaxed text-text/65">{check.reason}</p></div>) : <div className="w-64 rounded-lg border border-cyan/25 bg-cyan/5 p-3 text-sm text-cyan">No downstream exception was recorded.</div>}<div className="flex items-center text-text/35">→</div><div className={`w-56 rounded-lg border p-3 ${bid.scorecard.recommendation === "REJECT" ? "border-rose/30 bg-rose/10" : "border-cyan/30 bg-cyan/10"}`}><p className="font-mono text-[10px] uppercase text-text/45">Decision effect</p><p className="mt-2 text-sm font-semibold text-text">{reviewLabel(bid.scorecard.recommendation)}</p><p className="mt-1 text-xs text-text/60">A reviewer must confirm the evidence before acting.</p></div></div></div></Card>;
}
function Metric({ label, value }: { label: string; value: string }) { return <Card className="p-4"><p className="text-[10px] uppercase tracking-wide text-text/40">{label}</p><p className="mt-1 text-xl font-semibold text-text">{value}</p></Card>; }
function Loading() { return <div className="flex items-center justify-center gap-2 p-10 text-sm text-text/55"><LoaderCircle className="h-4 w-4 animate-spin" />Loading uploaded records…</div>; }
function Empty() { return <div className="p-10 text-center"><FileUp className="mx-auto h-6 w-6 text-text/35" /><p className="mt-3 text-sm font-medium text-text">No uploaded bids yet</p><p className="mt-1 text-xs text-text/50">Upload a text-based procurement PDF to start a deterministic review.</p></div>; }
function tabLabel(id: string) { return id === "summary" ? "Summary" : id === "checks" ? "Checks" : id === "impact" ? "Impact" : "Activity"; }
